feat: base lib integration

diff --git a/netmgr_wazuh b/netmgr_wazuh
--- a/netmgr_wazuh
+++ b/netmgr_wazuh
@@ -32,20 +32,20 @@ validate_ip() {
 validate_init(){
     [ $VERBOSE -eq 1 ] && echo "Validating initialization..."
 
-	[ -f "$NETMGR_RSYSLOG_PATH" ] && grep -Eq "^[ ]*#[ ]*<$NETMGR_MARKER_MAIN>" "$NETMGR_RSYSLOG_PATH" && return 0 || return 1
+	[ -f "$NETMGR_WAZUH_RSYSLOG_PATH" ] && grep -Eq "^[ ]*#[ ]*<$NETMGR_MARKER_MAIN>" "$NETMGR_WAZUH_RSYSLOG_PATH" && return 0 || return 1
 }
 
 validate_enable(){
     [ $VERBOSE -eq 1 ] && echo "Validating enable status..."
 
-	grep -Eq '^\$UDPServerRun 514' "$NETMGR_RSYSLOG_PATH" && grep -Eq '^\$ModLoad imudp' "$NETMGR_RSYSLOG_PATH" && return 0 || return 1
+	grep -Eq '^\$UDPServerRun 514' "$NETMGR_WAZUH_RSYSLOG_PATH" && grep -Eq '^\$ModLoad imudp' "$NETMGR_WAZUH_RSYSLOG_PATH" && return 0 || return 1
 }
 
 validate_node_exist(){
     [ $VERBOSE -eq 1 ] && echo "Validating node registration..."
 
 	local ip=$1
-	grep -Eq "# $NETMGR_MARKER_NODE-$ip" "$NETMGR_RSYSLOG_PATH" && return 0 || return 1
+	grep -Eq "# $NETMGR_MARKER_NODE-$ip" "$NETMGR_WAZUH_RSYSLOG_PATH" && return 0 || return 1
 }
 
 netmgr_clean_node(){
@@ -53,11 +53,11 @@ netmgr_clean_node(){
 	local ip=$1
 	local fullpath=""
 
-	grep ";$ip;" "$NETMGR_DATA_PATH" | while IFS=';' read -r path ip name library method username password; do
+	grep ";$ip;" "$NETMGR_WAZUH_DATA_PATH" | while IFS=';' read -r path ip name library method username password; do
 		if [[ -z "$path" || "$path" == "#"* ]]; then
 			continue
 		fi
-		fullpath="$NETMGR_LOG_PATH/$path"
+		fullpath="$NETMGR_WAZUH_LOG_PATH/$path"
 		[ $VERBOSE -eq 1 ] && echo "Node log path is $fullpath."
 
 		echo "" > "$fullpath"
@@ -75,7 +75,7 @@ netmgr_clean_file(){
 		if [[ -z "$path" || "$path" == "#"* ]]; then
 			continue
 		fi
-		fullpath="$NETMGR_LOG_PATH/$path"
+		fullpath="$NETMGR_WAZUH_LOG_PATH/$path"
 		[ $VERBOSE -eq 1 ] && echo "Node log path is $fullpath."
 
 		echo "" > "$fullpath"
@@ -93,9 +93,9 @@ netmgr_edit_node(){
 	local method=$5
 	local username=$6
 	local password=$7
-	local fullpath="$NETMGR_LOG_PATH/$path"
-	local libpath="$NETMGR_LIB_PATH/$library"
-	local line=$(grep ";$ip;" "$NETMGR_DATA_PATH")	
+	local fullpath="$NETMGR_WAZUH_LOG_PATH/$path"
+	local libpath="$NETMGR_WAZUH_LIB_PATH/$library"
+	local line=$(grep ";$ip;" "$NETMGR_WAZUH_DATA_PATH")	
 	local newline=""	
 
 	[ $VERBOSE -eq 1 ] && echo "Initial line is [$line]"
@@ -129,7 +129,7 @@ netmgr_edit_node(){
 
 	IFS=';' read -r file_path file_ip file_name file_library file_method file_username file_password <<< "$line"
 
-	local old_fullpath="$NETMGR_LOG_PATH/$file_path"
+	local old_fullpath="$NETMGR_WAZUH_LOG_PATH/$file_path"
 	local old_name="$file_name"
 	file_path=${path:-$file_path}
 	file_name=${name:-$file_name}
@@ -141,11 +141,11 @@ netmgr_edit_node(){
 	newline="$file_path;$ip;$file_name;$file_library;$file_method;$file_username;$file_password"
 	[ $VERBOSE -eq 1 ] && echo "New line is [$newline]"
 
-	sed -i "s|.*;$ip;.*|$newline|" "$NETMGR_DATA_PATH"
+	sed -i "s|.*;$ip;.*|$newline|" "$NETMGR_WAZUH_DATA_PATH"
 
 	if [ ! -z "$path" ]; then
 		[ $VERBOSE -eq 1 ] && echo "Editing path at rsyslog..."
-		sed -i "/# $NETMGR_MARKER_NODE-$ip/,/# \/$NETMGR_MARKER_NODE-$ip/ s|if \$fromhost-ip startswith '$ip' then $old_fullpath|if \$fromhost-ip startswith '$ip' then $fullpath|" "$NETMGR_RSYSLOG_PATH"
+		sed -i "/# $NETMGR_MARKER_NODE-$ip/,/# \/$NETMGR_MARKER_NODE-$ip/ s|if \$fromhost-ip startswith '$ip' then $old_fullpath|if \$fromhost-ip startswith '$ip' then $fullpath|" "$NETMGR_WAZUH_RSYSLOG_PATH"
 
 		[ $VERBOSE -eq 1 ] && echo "Editing path at ossec..."
 		sed -i "/<!-- $NETMGR_MARKER_NODE-$ip -->/,/<!-- \/$NETMGR_MARKER_NODE-$ip -->/ s|<location>$old_fullpath</location>|<location>$fullpath</location>|" "$WAZUH_CONF_PATH"
@@ -193,31 +193,25 @@ netmgr_register_node(){
 		return 1
 	elif [ "$method" != "none" ]; then
 		[ $VERBOSE -eq 1 ] && echo "Loading node library..."
-		libpath="$NETMGR_LIB_PATH/$library"
+		libpath="$NETMGR_WAZUH_LIB_PATH/$library"
+		base_libpath="$NETMGR_BASE_LIB_PATH/$library"
 
-		if [ ! -f "$libpath" ]; then
-			echo "Error: Library $libpath does not exist"
+		if [ ! -f "$libpath" ] || [ ! -f "$base_libpath" ]; then
+			echo "Error: Library does not exist"
 			return 1
 		fi	
 
 		(
+			source "$base_libpath"
 			source "$libpath"
 
 			[ $VERBOSE -eq 1 ] && echo "Gaining access to network appliance..."
-			case "$method" in
-			password)
-				lib_register_password $ip $username $password
-				;;
-			*)
-				echo "Error: Method $method is invalid or not available."
-				return 1
-				;;
-			esac
+			lib_register_node $method $ip $username $password
 		)
 		[ $? -ne 0 ] && return $?
 	fi
 
-	fullpath="$NETMGR_LOG_PATH/$path"
+	fullpath="$NETMGR_WAZUH_LOG_PATH/$path"
 
 	[ $VERBOSE -eq 1 ] && echo "
 Adding node:
@@ -230,7 +224,7 @@ name: $name
 	sed -i "/# <$NETMGR_MARKER_NODE>/a# $NETMGR_MARKER_NODE-$ip\\
 if \$fromhost-ip startswith '$ip' then $fullpath\\
 & ~\\
-# /$NETMGR_MARKER_NODE-$ip" "$NETMGR_RSYSLOG_PATH"
+# /$NETMGR_MARKER_NODE-$ip" "$NETMGR_WAZUH_RSYSLOG_PATH"
 
 	[ $VERBOSE -eq 1 ] && echo "Creating folder in given path..."
 	local dir=$(dirname "$fullpath")
@@ -254,7 +248,7 @@ sed -i "/<!-- $NETMGR_MARKER_MAIN -->/,/<!-- \/$NETMGR_MARKER_MAIN -->/ { /<osse
 }" "$WAZUH_CONF_PATH"
 
 	[ $VERBOSE -eq 1 ] && echo "Adding node data..."
-	echo "$path;$ip;$name;$library;$method;$username;$password" >> $NETMGR_DATA_PATH
+	echo "$path;$ip;$name;$library;$method;$username;$password" >> $NETMGR_WAZUH_DATA_PATH
 
 	echo "Node $ip has been added."
 }
@@ -305,34 +299,28 @@ netmgr_unregister_node(){
 		return 1
 	elif [ "$method" != "none" ]; then
 		[ $VERBOSE -eq 1 ] && echo "Loading node library..."
-		libpath="$NETMGR_LIB_PATH/$library"
+		libpath="$NETMGR_WAZUH_LIB_PATH/$library"
+		base_libpath="$NETMGR_BASE_LIB_PATH/$library"
 
-		if [ ! -f "$libpath" ]; then
-			echo "Error: Library $libpath does not exist"
+		if [ ! -f "$libpath" ] || [ ! -f "$base_libpath" ]; then
+			echo "Error: Library does not exist"
 			return 1
 		fi	
 
 		(
+			source "$base_libpath"
 			source "$libpath"
 
 			[ $VERBOSE -eq 1 ] && echo "Gaining access to network appliance..."
-			case "$method" in
-			password)
-				lib_unregister_password $ip $username $password
-				;;
-			*)
-				echo "Error: Method $method is invalid or not available."
-				return 1
-				;;
-			esac
+			lib_unregister_node $method $ip $username $password
 		)
 		[ $? -ne 0 ] && return $?
 	fi
 
-	fullpath="$NETMGR_LOG_PATH/$path"
+	fullpath="$NETMGR_WAZUH_LOG_PATH/$path"
 
 	[ $VERBOSE -eq 1 ] && echo "Removing node from rsyslog configuration..."
-	sed -i "/# $NETMGR_MARKER_NODE-$ip/,/# \/$NETMGR_MARKER_NODE-$ip/d" "$NETMGR_RSYSLOG_PATH"
+	sed -i "/# $NETMGR_MARKER_NODE-$ip/,/# \/$NETMGR_MARKER_NODE-$ip/d" "$NETMGR_WAZUH_RSYSLOG_PATH"
 
 	[ $VERBOSE -eq 1 ] && echo "Deleting node log file..."
 	[ -f "$fullpath" ] && rm "$fullpath"
@@ -341,7 +329,7 @@ netmgr_unregister_node(){
 	sed -i "/<!-- $NETMGR_MARKER_NODE-$ip -->/,/<!-- \/$NETMGR_MARKER_NODE-$ip -->/d" "$WAZUH_CONF_PATH"
 
 	[ $VERBOSE -eq 1 ] && echo "Deleting node from data..."
-	sed "/;$ip;/d" "$NETMGR_DATA_PATH" > "${NETMGR_DATA_PATH}.tmp" && mv "${NETMGR_DATA_PATH}.tmp" "$NETMGR_DATA_PATH"
+	sed "/;$ip;/d" "$NETMGR_WAZUH_DATA_PATH" > "${NETMGR_WAZUH_DATA_PATH}.tmp" && mv "${NETMGR_WAZUH_DATA_PATH}.tmp" "$NETMGR_WAZUH_DATA_PATH"
 
 	echo "Node $ip has been removed."
 }
@@ -411,7 +399,7 @@ func_init(){
 		echo '# $UDPServerRun 514'
 		echo ''
 		echo "# <$NETMGR_MARKER_NODE>"
-		} > "$NETMGR_RSYSLOG_PATH"
+		} > "$NETMGR_WAZUH_RSYSLOG_PATH"
 
 		[ $VERBOSE -eq 1 ] && echo "Setting up ossec configs..."
 		{
@@ -422,11 +410,11 @@ func_init(){
 		} >> "$WAZUH_CONF_PATH"
 
 		[ $VERBOSE -eq 1 ] && echo "Creating folder for data file..."
-		local dir=$(dirname "$NETMGR_DATA_PATH")
+		local dir=$(dirname "$NETMGR_WAZUH_DATA_PATH")
 		mkdir -p "$dir"
 
 		[ $VERBOSE -eq 1 ] && echo "Creating data file..."
-		touch "$NETMGR_DATA_PATH"
+		touch "$NETMGR_WAZUH_DATA_PATH"
 
 		echo "Wazuh Netmanager setup complete."
 	fi
@@ -436,16 +424,16 @@ func_reset(){
 	[ $VERBOSE -eq 1 ] && echo "Resetting Wazuh..."
 
 	[ $VERBOSE -eq 1 ] && echo "Setting off all network appliances logging..."
-	netmgr_unregister_file "$NETMGR_DATA_PATH"
+	netmgr_unregister_file "$NETMGR_WAZUH_DATA_PATH"
 
 	[ $VERBOSE -eq 1 ] && echo "Deleting Wazuh Netmanager rsyslog configs..."
-	[ -f "$NETMGR_RSYSLOG_PATH" ] && rm $NETMGR_RSYSLOG_PATH
+	[ -f "$NETMGR_WAZUH_RSYSLOG_PATH" ] && rm $NETMGR_WAZUH_RSYSLOG_PATH
 
 	[ $VERBOSE -eq 1 ] && echo "Deleting Wazuh Netmanager ossec configs..."
 	sed -i "/<!-- $NETMGR_MARKER_MAIN -->/,/<!-- \/$NETMGR_MARKER_MAIN -->/d" "$WAZUH_CONF_PATH"
 	
 	[ $VERBOSE -eq 1 ] && echo "Deleting Netmanager ossec data..."
-	[ -f "$NETMGR_DATA_PATH" ] && rm "$NETMGR_DATA_PATH"
+	[ -f "$NETMGR_WAZUH_DATA_PATH" ] && rm "$NETMGR_WAZUH_DATA_PATH"
 
 	echo "Wazuh Netmanager has been reset. Use \"netmgr_wazuh reload\" for it to take effect."
 }
@@ -485,7 +473,7 @@ Example file format at ./data/netmgr_wazuh.data.example
 			echo "Error: -a flag cannot be used at the same time with file or single entry flag"
 			exit 1
 		fi
-		netmgr_clean_file "$NETMGR_DATA_PATH"
+		netmgr_clean_file "$NETMGR_WAZUH_DATA_PATH"
 	elif [ ! -z "$file" ]; then
 		if [ ! -z "$ip" ]; then 
 			echo "Error: -f flag cannot be used at the same time with singular entry flag"
@@ -514,7 +502,7 @@ func_status(){
 
 	validate_init && initialized="True" || initialized="False"
 	validate_enable && enabled="True" || enabled="False"
-	node_count=$(grep -cE "# $NETMGR_MARKER_NODE-.+" "$NETMGR_RSYSLOG_PATH")
+	node_count=$(grep -cE "# $NETMGR_MARKER_NODE-.+" "$NETMGR_WAZUH_RSYSLOG_PATH")
 
 	echo "
 Wazuh Netmanager status:
@@ -530,11 +518,11 @@ Nodes:"
 		echo "$counter.
 	Name: $name
 	ip address: $ip
-	logpath: $NETMGR_LOG_PATH/$path
+	logpath: $NETMGR_WAZUH_LOG_PATH/$path
 	library: $library"
 
 		((counter++))	
-	done < "$NETMGR_DATA_PATH"
+	done < "$NETMGR_WAZUH_DATA_PATH"
 
 	echo ""
 }
@@ -544,16 +532,16 @@ func_enable(){
    
 	local count=0
 
-	if grep -Eq '^[ ]*#[ ]*\$UDPServerRun 514' "$NETMGR_RSYSLOG_PATH"; then
+	if grep -Eq '^[ ]*#[ ]*\$UDPServerRun 514' "$NETMGR_WAZUH_RSYSLOG_PATH"; then
 		[ $VERBOSE -eq 1 ] && echo "ServerRun line is commented out" 
-		sed -i 's/^[ ]*#[ ]*\$UDPServerRun 514/\$UDPServerRun 514/' "$NETMGR_RSYSLOG_PATH"  
+		sed -i 's/^[ ]*#[ ]*\$UDPServerRun 514/\$UDPServerRun 514/' "$NETMGR_WAZUH_RSYSLOG_PATH"  
 	else
 		((count++))
 	fi
 
-	if grep -Eq '^[ ]*#[ ]*\$ModLoad imudp' "$NETMGR_RSYSLOG_PATH"; then
+	if grep -Eq '^[ ]*#[ ]*\$ModLoad imudp' "$NETMGR_WAZUH_RSYSLOG_PATH"; then
 		[ $VERBOSE -eq 1 ] && echo "ModLoad line is commented out" 
-		sed -i 's/^[ ]*#[ ]*\$ModLoad imudp/\$ModLoad imudp/' "$NETMGR_RSYSLOG_PATH"
+		sed -i 's/^[ ]*#[ ]*\$ModLoad imudp/\$ModLoad imudp/' "$NETMGR_WAZUH_RSYSLOG_PATH"
 	else
 		((count++))
 	fi	
@@ -570,16 +558,16 @@ func_disable(){
 
 	local count=0
 
-	if grep -Eq '^[ ]*\$ModLoad imudp' "$NETMGR_RSYSLOG_PATH"; then
+	if grep -Eq '^[ ]*\$ModLoad imudp' "$NETMGR_WAZUH_RSYSLOG_PATH"; then
 		[ $VERBOSE -eq 1 ] && echo "Commenting ModLoad line"
-		sed -i 's/^[ ]*\$ModLoad imudp/# \$ModLoad imudp/' "$NETMGR_RSYSLOG_PATH"
+		sed -i 's/^[ ]*\$ModLoad imudp/# \$ModLoad imudp/' "$NETMGR_WAZUH_RSYSLOG_PATH"
 	else
 		((count++))
 	fi
 	
-	if grep -Eq '^[ ]*\$UDPServerRun 514' "$NETMGR_RSYSLOG_PATH"; then
+	if grep -Eq '^[ ]*\$UDPServerRun 514' "$NETMGR_WAZUH_RSYSLOG_PATH"; then
 		[ $VERBOSE -eq 1 ] && echo "Commenting ServerRun line"
-		sed -i 's/^[ ]*\$UDPServerRun 514/# \$UDPServerRun 514/' "$NETMGR_RSYSLOG_PATH"
+		sed -i 's/^[ ]*\$UDPServerRun 514/# \$UDPServerRun 514/' "$NETMGR_WAZUH_RSYSLOG_PATH"
 	else
 		((count++))
 	fi
@@ -719,7 +707,7 @@ func_unregister(){
 		[ $? -ne 0 ] && exit $?
 
 	elif [ ! -z "$ip" ]; then
-		grep ";$ip;" "$NETMGR_DATA_PATH" | while IFS=';' read -r path ip name library method username password; do
+		grep ";$ip;" "$NETMGR_WAZUH_DATA_PATH" | while IFS=';' read -r path ip name library method username password; do
 			if [[ -z "$path" || "$path" == "#"* ]]; then
 				continue
 			fi
